# -*- coding: utf-8 -*-
"""Student Data Analysis22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1du8T9eXy8JfiDecwOHJJXEtUASMJzN1W

Install faker
"""

pip install faker

from faker import Faker

fake= Faker()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(0)

import pandas as pd

"""Create a Data:"""

names = [fake.name() for _ in range(250)]
data={
    "Student_Id" :np.arange(1,251),
    "Name" :np.random.choice(names, 250),
    "Gender" :np.random.choice(["male","female"],250),
    "Department" :np.random.choice(["HR","IT","Finance","Marketing"],250),
    "Year":np.random.randint(2025,2028,250),
    "Maths":np.random.randint(0,100,250),
    "Science":np.random.randint(0,100,250),
    "English":np.random.randint(0,100,250),
    "Attendance":np.random.randint(50,100,250),
    "Internal Marks":np.random.randint(0,25,250),
}

df=pd.DataFrame(data)

df

df.isnull().sum()

df["Total"] = df["Maths"] + df["Science"] + df["English"]
df["Average"] = df["Total"] / 3

df["Grade"] = df["Average"].apply(lambda x: "A" if x>=85 else "B" if x>=70 else "C" if x>=50 else "Fail")

print("\nTop Students:\n", df.nlargest(5, "Average")[["Name","Average","Grade"]])

"""Bar Chart"""

plt.scatter(df["Attendance"], df["Average"])
plt.xlabel("Attendance")
plt.ylabel("Average Marks")
plt.title("Attendance vs Performance")
plt.show()

"""Pie Chart"""

plt.figure()
df["Gender"].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Gender Distribution")
plt.ylabel("")
plt.show()

"""Histogram"""

plt.figure()
plt.hist(df["Average"], bins=10)
plt.title("Distribution of Average Marks")
plt.xlabel("Average Marks")
plt.ylabel("Frequency")
plt.show()

"""Scatter Plot"""

plt.figure()
plt.scatter(df["Attendance"], df["Average"])
plt.title("Attendance vs Average Marks")
plt.xlabel("Attendance")
plt.ylabel("Average Marks")
plt.show()